import "./globals.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";

config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: {
 children: React.ReactNode;
}) {
 return (
  <html lang="en">
   <Head>
    <link
     rel="stylesheet"
     href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
     integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
     crossOrigin="anonymous"
     referrerPolicy="no-referrer"
    />
   </Head>
   <body className={`${inter.className} px-10 pt-5 bg-zinc-900 font-sans`}>
    <Toaster position="bottom-right" reverseOrder={false} />
    <Navbar />
    {children}
   </body>
  </html>
 );
}
