import "./globals.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";
import { dir } from "i18next";
import { useTranslation } from "../i18n";

config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata = {
 title: "Real Testing",
 description: "Generated by create next app",
};

export default async function RootLayout({
 children,
 params,
}: {
 children: React.ReactNode;
 params: { lng: string };
}) {
 const { t } = await useTranslation(params.lng);
 return (
  <html lang={params.lng} dir={dir(params.lng)}>
   <Head>
    <link
     rel="stylesheet"
     href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
     integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
     crossOrigin="anonymous"
     referrerPolicy="no-referrer"
    />
   </Head>
   <body className={`${inter.variable} px-10 pt-5 bg-zinc-900 font-sans`}>
    <Toaster position="bottom-right" reverseOrder={false} />
    {/* @ts-expect-error Server Component */}
    <Navbar t={t} lng={params.lng} />
    {children}
   </body>
  </html>
 );
}
